spring.datasource.url=jdbc:postgresql://localhost:5432/performance_db
spring.datasource.username=postgres
spring.datasource.password=C0nsult0ri26**
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwtSecret=JWTSuperSecretKeyForPerformanceManagementSystem2024SecureEnoughForHS512Algorithm!
app.jwtExpirationInMs=86400000

# Configuración de Correo ("El Cartero")
# Esta es la cuenta que el SISTEMA usará para ENVIAR los correos a los usuarios.
# NO es el correo del usuario que recupera la contraseña.
# Debe ser una cuenta real de Gmail (u otro) controlada por ti (el administrador).
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juanjose01212@gmail.com
spring.mail.password=eawy whoj qptc csfv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080
